# Generated by Django 4.1.5 on 2023-02-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_timesheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='name',
        ),
    ]
