# Generated by Django 4.1.5 on 2023-02-23 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_remove_timesheet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='reporting_manager',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
